# ESTE PEQUEÑO CODIGO ES UN EJEMPLO SENCILLO PARA CONECTAR AL SERVIDOR
# PRIMERO HAY QUE TENER CORRIENDO SERVIDOR Y MONITOR
# LUEGO EJECUTAMOS ESTE CODIGO E INICIAMOS 
# EL PARTIDO EN EL SERVIDOR (en la opccion referee/kickOff)

import sys
import os
import time

sys.path.append('./src')

from src.Jugador import Jugador

# INSTANCIAMOS UN JUGADOR
p = Jugador("goleador")

# ORDEMANOS QUE EL JUGADOR SEA MOVIDO A LA POSICION -10, 0
p.sendCommand("(move -10 0)")

# ESTA VARIABLE ES PARA DETERMINAR CUANDO VAMOS A TERMINAR ESTA
# PRUEBA
stop = False

# ESTABLECEMOS EL MOMENTO EN EL QUE INICIAMOS
start = time.time()
t = 0
# ESTE INCREMENTO ES PARA REFRESCAR LA PANTALLA DE LA CONSOLA
# CADA 0.5s
deltaT = 0.5

# INICIAMOS EL CICLO
while not stop:
	
	# CADA CICLO VAMOS A ESTAR ACTUALIZANDO EL ESTADO DEL JUGADOR
	p.updateState()
	
	# A LA AVEZ VAMOS A ESTAR MANDANDO AL JUGADOR
	# LA INSTRUCCION DE QUE CORRA
	# HACIA ENFRENTE CON SU MAXIMA POTENCIA
	p.sendCommand("(dash 100)")
	
	# SI HAN PASADO 0.5s REFRESCA LA PANTALLA
	if t > deltaT:
		os.system('clear')
		p.printBodyState()
		deltaT = t + 0.5
	
	# SE CALCULA CUANDO TIEMPO HA PASADO EN LA EJECUCION DE 
	# ESTE CICLO
	t = time.time() - start
	
	# SI HAN PASADO 30 SEGUNDOS SE TERMINA EL CICLO
	if t > 30:
		stop = True

# EL JUGADOR MANDA SU COMANDO PARA DESCONECTARSE DEL SERVIDOR
p.bye()


